/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * 야덕연구소 API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Team {
  id: number;
  name: string;
  shortName: string;
  /** @nullable */
  logoUrl?: string | null;
  primaryColor: string;
  wins: number;
  losses: number;
  draws: number;
  winRate: number;
  rank: number;
  city: string;
}

export interface Player {
  id: number;
  name: string;
  teamId: number;
  /** @nullable */
  teamName?: string | null;
  /** @nullable */
  teamColor?: string | null;
  position: string;
  /** @nullable */
  backNumber?: number | null;
  /** @nullable */
  photoUrl?: string | null;
  /** @nullable */
  battingAvg?: number | null;
  /** @nullable */
  homeRuns?: number | null;
  /** @nullable */
  rbi?: number | null;
  /** @nullable */
  ops?: number | null;
  /** @nullable */
  war?: number | null;
  /** @nullable */
  era?: number | null;
  nationality: string;
}

export interface PlayerStats {
  playerId: number;
  season: number;
  games: number;
  /** @nullable */
  atBats?: number | null;
  /** @nullable */
  hits?: number | null;
  /** @nullable */
  doubles?: number | null;
  /** @nullable */
  triples?: number | null;
  /** @nullable */
  homeRuns?: number | null;
  /** @nullable */
  rbi?: number | null;
  /** @nullable */
  runs?: number | null;
  /** @nullable */
  stolenBases?: number | null;
  /** @nullable */
  walks?: number | null;
  /** @nullable */
  strikeouts?: number | null;
  /** @nullable */
  battingAvg?: number | null;
  /** @nullable */
  obp?: number | null;
  /** @nullable */
  slg?: number | null;
  /** @nullable */
  ops?: number | null;
  /** @nullable */
  war?: number | null;
  /** @nullable */
  wins?: number | null;
  /** @nullable */
  losses?: number | null;
  /** @nullable */
  era?: number | null;
  /** @nullable */
  whip?: number | null;
  /** @nullable */
  inningsPitched?: number | null;
  /** @nullable */
  aiReport?: string | null;
}

export interface GameLog {
  date: string;
  opponent: string;
  result: string;
  /** @nullable */
  atBats?: number | null;
  /** @nullable */
  hits?: number | null;
  /** @nullable */
  homeRuns?: number | null;
  /** @nullable */
  rbi?: number | null;
  /** @nullable */
  battingAvg?: number | null;
  /** @nullable */
  inningsPitched?: number | null;
  /** @nullable */
  era?: number | null;
}

export type MatchStatus = typeof MatchStatus[keyof typeof MatchStatus];


export const MatchStatus = {
  scheduled: 'scheduled',
  live: 'live',
  completed: 'completed',
} as const;

export interface Match {
  id: number;
  homeTeamId: number;
  awayTeamId: number;
  homeTeamName: string;
  awayTeamName: string;
  homeTeamColor: string;
  awayTeamColor: string;
  /** @nullable */
  homeScore?: number | null;
  /** @nullable */
  awayScore?: number | null;
  status: MatchStatus;
  scheduledAt: string;
  venue: string;
  /** @nullable */
  inning?: number | null;
  /** @nullable */
  inningHalf?: string | null;
  /** @nullable */
  aiSummary?: string | null;
}

export interface Post {
  id: number;
  title: string;
  content: string;
  board: string;
  authorId: number;
  authorName: string;
  authorGrade: string;
  views: number;
  upvotes: number;
  downvotes: number;
  commentCount: number;
  createdAt: string;
  updatedAt: string;
  isHot: boolean;
}

export type PostInputBoard = typeof PostInputBoard[keyof typeof PostInputBoard];


export const PostInputBoard = {
  free: 'free',
  kbo: 'kbo',
  mlb: 'mlb',
  prospects: 'prospects',
  trades: 'trades',
} as const;

export interface PostInput {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  content: string;
  board: PostInputBoard;
  authorId: number;
}

export interface PostUpdate {
  title?: string;
  content?: string;
}

export type VoteInputType = typeof VoteInputType[keyof typeof VoteInputType];


export const VoteInputType = {
  up: 'up',
  down: 'down',
} as const;

export interface VoteInput {
  type: VoteInputType;
  userId: number;
}

export interface Comment {
  id: number;
  postId: number;
  content: string;
  authorId: number;
  authorName: string;
  authorGrade: string;
  createdAt: string;
}

export interface CommentInput {
  /** @minLength 1 */
  content: string;
  authorId: number;
}

export interface Prediction {
  id: number;
  type: string;
  userId: number;
  userName: string;
  /** @nullable */
  targetId?: number | null;
  targetName: string;
  date: string;
  /** @nullable */
  isCorrect?: boolean | null;
  /** @nullable */
  pointsEarned?: number | null;
  createdAt: string;
}

export type PredictionInputType = typeof PredictionInputType[keyof typeof PredictionInputType];


export const PredictionInputType = {
  homerun: 'homerun',
  mvp: 'mvp',
  weekly_batting: 'weekly_batting',
  season_champion: 'season_champion',
} as const;

export interface PredictionInput {
  type: PredictionInputType;
  userId: number;
  targetId?: number;
  targetName: string;
  date: string;
}

export interface LeaderboardEntry {
  userId: number;
  userName: string;
  userGrade: string;
  totalPoints: number;
  correctCount: number;
  totalCount: number;
  accuracy: number;
  rank: number;
}

export interface User {
  id: number;
  username: string;
  email: string;
  grade: string;
  gradeLabel: string;
  points: number;
  experience: number;
  /** @nullable */
  favoriteTeamId?: number | null;
  /** @nullable */
  favoriteTeamName?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  bio?: string | null;
  postCount: number;
  commentCount: number;
  predictionCount: number;
  correctPredictions: number;
  /** @nullable */
  lastCheckin?: string | null;
  createdAt: string;
}

export interface UserUpdate {
  username?: string;
  bio?: string;
  favoriteTeamId?: number;
  avatarUrl?: string;
}

export interface RegisterInput {
  /** @minLength 2 */
  username: string;
  email: string;
  /** @minLength 6 */
  password: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface AuthResult {
  user: User;
  token: string;
}

export interface CheckinResult {
  pointsEarned: number;
  totalPoints: number;
  streak: number;
  message: string;
}

export type PlayerCardRarity = typeof PlayerCardRarity[keyof typeof PlayerCardRarity];


export const PlayerCardRarity = {
  common: 'common',
  rare: 'rare',
  hero: 'hero',
  legend: 'legend',
} as const;

export interface PlayerCard {
  id: number;
  userId: number;
  playerId: number;
  playerName: string;
  /** @nullable */
  playerPhoto?: string | null;
  teamName: string;
  rarity: PlayerCardRarity;
  acquiredAt: string;
}

export interface Achievement {
  id: number;
  name: string;
  description: string;
  /** @nullable */
  iconUrl?: string | null;
  /** @nullable */
  earnedAt?: string | null;
  isEarned: boolean;
}

export interface Highlight {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  videoUrl: string;
  /** @nullable */
  thumbnailUrl?: string | null;
  category: string;
  uploaderId: number;
  uploaderName: string;
  views: number;
  likes: number;
  createdAt: string;
}

export type HighlightInputCategory = typeof HighlightInputCategory[keyof typeof HighlightInputCategory];


export const HighlightInputCategory = {
  legendary: 'legendary',
  walkoff_hr: 'walkoff_hr',
  great_defense: 'great_defense',
  all: 'all',
} as const;

export interface HighlightInput {
  /** @minLength 1 */
  title: string;
  description?: string;
  videoUrl: string;
  thumbnailUrl?: string;
  category: HighlightInputCategory;
  uploaderId: number;
}

export interface HomeSummary {
  todayMatchCount: number;
  liveMatchCount: number;
  totalPostCount: number;
  activePredictions: number;
  topTeam?: Team;
  hotPost?: Post;
}

export interface AiMatchPrediction {
  matchId: number;
  homeTeam: string;
  awayTeam: string;
  predictedWinner: string;
  confidence: number;
  reasoning: string;
}

export interface HomerunCandidate {
  playerId: number;
  playerName: string;
  teamName: string;
  probability: number;
  recentForm: string;
  homeRuns: number;
}

export interface Notification {
  id: number;
  userId: number;
  type: string;
  message: string;
  isRead: boolean;
  createdAt: string;
}

export type ListPlayersParams = {
search?: string;
teamId?: number;
position?: string;
limit?: number;
};

export type GetTopHittersParams = {
limit?: number;
};

export type ListMatchesParams = {
date?: string;
status?: ListMatchesStatus;
limit?: number;
};

export type ListMatchesStatus = typeof ListMatchesStatus[keyof typeof ListMatchesStatus];


export const ListMatchesStatus = {
  scheduled: 'scheduled',
  live: 'live',
  completed: 'completed',
} as const;

export type ListPostsParams = {
board?: ListPostsBoard;
sort?: ListPostsSort;
limit?: number;
offset?: number;
};

export type ListPostsBoard = typeof ListPostsBoard[keyof typeof ListPostsBoard];


export const ListPostsBoard = {
  free: 'free',
  kbo: 'kbo',
  mlb: 'mlb',
  prospects: 'prospects',
  trades: 'trades',
} as const;

export type ListPostsSort = typeof ListPostsSort[keyof typeof ListPostsSort];


export const ListPostsSort = {
  latest: 'latest',
  popular: 'popular',
  views: 'views',
} as const;

export type GetPopularPostsParams = {
limit?: number;
};

export type ListPredictionsParams = {
type?: ListPredictionsType;
date?: string;
};

export type ListPredictionsType = typeof ListPredictionsType[keyof typeof ListPredictionsType];


export const ListPredictionsType = {
  homerun: 'homerun',
  mvp: 'mvp',
  weekly_batting: 'weekly_batting',
  season_champion: 'season_champion',
} as const;

export type GetPredictionLeaderboardParams = {
limit?: number;
};

export type ListHighlightsParams = {
category?: ListHighlightsCategory;
sort?: ListHighlightsSort;
limit?: number;
};

export type ListHighlightsCategory = typeof ListHighlightsCategory[keyof typeof ListHighlightsCategory];


export const ListHighlightsCategory = {
  legendary: 'legendary',
  walkoff_hr: 'walkoff_hr',
  great_defense: 'great_defense',
  all: 'all',
} as const;

export type ListHighlightsSort = typeof ListHighlightsSort[keyof typeof ListHighlightsSort];


export const ListHighlightsSort = {
  latest: 'latest',
  views: 'views',
  likes: 'likes',
} as const;

