/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * 야덕연구소 API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Achievement,
  AiMatchPrediction,
  AuthResult,
  CheckinResult,
  Comment,
  CommentInput,
  GameLog,
  GetPopularPostsParams,
  GetPredictionLeaderboardParams,
  GetTopHittersParams,
  HealthStatus,
  Highlight,
  HighlightInput,
  HomeSummary,
  HomerunCandidate,
  LeaderboardEntry,
  ListHighlightsParams,
  ListMatchesParams,
  ListPlayersParams,
  ListPostsParams,
  ListPredictionsParams,
  LoginInput,
  Match,
  Notification,
  Player,
  PlayerCard,
  PlayerStats,
  Post,
  PostInput,
  PostUpdate,
  Prediction,
  PredictionInput,
  RegisterInput,
  Team,
  User,
  UserUpdate,
  VoteInput
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListTeamsUrl = () => {




  return `/api/teams`
}

/**
 * @summary List all teams with standings
 */
export const listTeams = async ( options?: RequestInit): Promise<Team[]> => {

  return customFetch<Team[]>(getListTeamsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTeamsQueryKey = () => {
    return [
    `/api/teams`
    ] as const;
    }


export const getListTeamsQueryOptions = <TData = Awaited<ReturnType<typeof listTeams>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTeams>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTeamsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTeams>>> = ({ signal }) => listTeams({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTeams>>, TError, TData> & { queryKey: QueryKey }
}

export type ListTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof listTeams>>>
export type ListTeamsQueryError = ErrorType<unknown>


/**
 * @summary List all teams with standings
 */

export function useListTeams<TData = Awaited<ReturnType<typeof listTeams>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTeams>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListTeamsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetTeamUrl = (id: number,) => {




  return `/api/teams/${id}`
}

export const getTeam = async (id: number, options?: RequestInit): Promise<Team> => {

  return customFetch<Team>(getGetTeamUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTeamQueryKey = (id: number,) => {
    return [
    `/api/teams/${id}`
    ] as const;
    }


export const getGetTeamQueryOptions = <TData = Awaited<ReturnType<typeof getTeam>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTeam>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeamQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeam>>> = ({ signal }) => getTeam(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeam>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTeamQueryResult = NonNullable<Awaited<ReturnType<typeof getTeam>>>
export type GetTeamQueryError = ErrorType<unknown>



export function useGetTeam<TData = Awaited<ReturnType<typeof getTeam>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTeam>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTeamQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListPlayersUrl = (params?: ListPlayersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/players?${stringifiedParams}` : `/api/players`
}

export const listPlayers = async (params?: ListPlayersParams, options?: RequestInit): Promise<Player[]> => {

  return customFetch<Player[]>(getListPlayersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPlayersQueryKey = (params?: ListPlayersParams,) => {
    return [
    `/api/players`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPlayersQueryOptions = <TData = Awaited<ReturnType<typeof listPlayers>>, TError = ErrorType<unknown>>(params?: ListPlayersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPlayers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPlayersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlayers>>> = ({ signal }) => listPlayers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPlayers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPlayersQueryResult = NonNullable<Awaited<ReturnType<typeof listPlayers>>>
export type ListPlayersQueryError = ErrorType<unknown>



export function useListPlayers<TData = Awaited<ReturnType<typeof listPlayers>>, TError = ErrorType<unknown>>(
 params?: ListPlayersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPlayers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPlayersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetPlayerUrl = (id: number,) => {




  return `/api/players/${id}`
}

export const getPlayer = async (id: number, options?: RequestInit): Promise<Player> => {

  return customFetch<Player>(getGetPlayerUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlayerQueryKey = (id: number,) => {
    return [
    `/api/players/${id}`
    ] as const;
    }


export const getGetPlayerQueryOptions = <TData = Awaited<ReturnType<typeof getPlayer>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlayerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayer>>> = ({ signal }) => getPlayer(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlayerQueryResult = NonNullable<Awaited<ReturnType<typeof getPlayer>>>
export type GetPlayerQueryError = ErrorType<unknown>



export function useGetPlayer<TData = Awaited<ReturnType<typeof getPlayer>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlayer>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPlayerQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetPlayerStatsUrl = (id: number,) => {




  return `/api/players/${id}/stats`
}

export const getPlayerStats = async (id: number, options?: RequestInit): Promise<PlayerStats> => {

  return customFetch<PlayerStats>(getGetPlayerStatsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlayerStatsQueryKey = (id: number,) => {
    return [
    `/api/players/${id}/stats`
    ] as const;
    }


export const getGetPlayerStatsQueryOptions = <TData = Awaited<ReturnType<typeof getPlayerStats>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlayerStatsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayerStats>>> = ({ signal }) => getPlayerStats(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlayerStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getPlayerStats>>>
export type GetPlayerStatsQueryError = ErrorType<unknown>



export function useGetPlayerStats<TData = Awaited<ReturnType<typeof getPlayerStats>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlayerStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPlayerStatsQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetPlayerRecentGamesUrl = (id: number,) => {




  return `/api/players/${id}/recent`
}

export const getPlayerRecentGames = async (id: number, options?: RequestInit): Promise<GameLog[]> => {

  return customFetch<GameLog[]>(getGetPlayerRecentGamesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPlayerRecentGamesQueryKey = (id: number,) => {
    return [
    `/api/players/${id}/recent`
    ] as const;
    }


export const getGetPlayerRecentGamesQueryOptions = <TData = Awaited<ReturnType<typeof getPlayerRecentGames>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlayerRecentGames>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPlayerRecentGamesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlayerRecentGames>>> = ({ signal }) => getPlayerRecentGames(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPlayerRecentGames>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPlayerRecentGamesQueryResult = NonNullable<Awaited<ReturnType<typeof getPlayerRecentGames>>>
export type GetPlayerRecentGamesQueryError = ErrorType<unknown>



export function useGetPlayerRecentGames<TData = Awaited<ReturnType<typeof getPlayerRecentGames>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPlayerRecentGames>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPlayerRecentGamesQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetTopHittersUrl = (params?: GetTopHittersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/players/top/hitters?${stringifiedParams}` : `/api/players/top/hitters`
}

/**
 * @summary Top batting average leaders
 */
export const getTopHitters = async (params?: GetTopHittersParams, options?: RequestInit): Promise<Player[]> => {

  return customFetch<Player[]>(getGetTopHittersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTopHittersQueryKey = (params?: GetTopHittersParams,) => {
    return [
    `/api/players/top/hitters`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTopHittersQueryOptions = <TData = Awaited<ReturnType<typeof getTopHitters>>, TError = ErrorType<unknown>>(params?: GetTopHittersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTopHitters>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopHittersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopHitters>>> = ({ signal }) => getTopHitters(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopHitters>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTopHittersQueryResult = NonNullable<Awaited<ReturnType<typeof getTopHitters>>>
export type GetTopHittersQueryError = ErrorType<unknown>


/**
 * @summary Top batting average leaders
 */

export function useGetTopHitters<TData = Awaited<ReturnType<typeof getTopHitters>>, TError = ErrorType<unknown>>(
 params?: GetTopHittersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTopHitters>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTopHittersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListMatchesUrl = (params?: ListMatchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/matches?${stringifiedParams}` : `/api/matches`
}

export const listMatches = async (params?: ListMatchesParams, options?: RequestInit): Promise<Match[]> => {

  return customFetch<Match[]>(getListMatchesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMatchesQueryKey = (params?: ListMatchesParams,) => {
    return [
    `/api/matches`, ...(params ? [params] : [])
    ] as const;
    }


export const getListMatchesQueryOptions = <TData = Awaited<ReturnType<typeof listMatches>>, TError = ErrorType<unknown>>(params?: ListMatchesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMatchesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMatches>>> = ({ signal }) => listMatches(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof listMatches>>>
export type ListMatchesQueryError = ErrorType<unknown>



export function useListMatches<TData = Awaited<ReturnType<typeof listMatches>>, TError = ErrorType<unknown>>(
 params?: ListMatchesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMatches>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListMatchesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMatchUrl = (id: number,) => {




  return `/api/matches/${id}`
}

export const getMatch = async (id: number, options?: RequestInit): Promise<Match> => {

  return customFetch<Match>(getGetMatchUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMatchQueryKey = (id: number,) => {
    return [
    `/api/matches/${id}`
    ] as const;
    }


export const getGetMatchQueryOptions = <TData = Awaited<ReturnType<typeof getMatch>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMatchQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMatch>>> = ({ signal }) => getMatch(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMatchQueryResult = NonNullable<Awaited<ReturnType<typeof getMatch>>>
export type GetMatchQueryError = ErrorType<unknown>



export function useGetMatch<TData = Awaited<ReturnType<typeof getMatch>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMatch>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMatchQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetTodayMatchesUrl = () => {




  return `/api/matches/today`
}

/**
 * @summary Today's matches
 */
export const getTodayMatches = async ( options?: RequestInit): Promise<Match[]> => {

  return customFetch<Match[]>(getGetTodayMatchesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTodayMatchesQueryKey = () => {
    return [
    `/api/matches/today`
    ] as const;
    }


export const getGetTodayMatchesQueryOptions = <TData = Awaited<ReturnType<typeof getTodayMatches>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTodayMatches>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodayMatchesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodayMatches>>> = ({ signal }) => getTodayMatches({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodayMatches>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTodayMatchesQueryResult = NonNullable<Awaited<ReturnType<typeof getTodayMatches>>>
export type GetTodayMatchesQueryError = ErrorType<unknown>


/**
 * @summary Today's matches
 */

export function useGetTodayMatches<TData = Awaited<ReturnType<typeof getTodayMatches>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTodayMatches>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTodayMatchesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListPostsUrl = (params?: ListPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/posts?${stringifiedParams}` : `/api/posts`
}

export const listPosts = async (params?: ListPostsParams, options?: RequestInit): Promise<Post[]> => {

  return customFetch<Post[]>(getListPostsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPostsQueryKey = (params?: ListPostsParams,) => {
    return [
    `/api/posts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPostsQueryOptions = <TData = Awaited<ReturnType<typeof listPosts>>, TError = ErrorType<unknown>>(params?: ListPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPostsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPosts>>> = ({ signal }) => listPosts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPostsQueryResult = NonNullable<Awaited<ReturnType<typeof listPosts>>>
export type ListPostsQueryError = ErrorType<unknown>



export function useListPosts<TData = Awaited<ReturnType<typeof listPosts>>, TError = ErrorType<unknown>>(
 params?: ListPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPostsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreatePostUrl = () => {




  return `/api/posts`
}

export const createPost = async (postInput: PostInput, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getCreatePostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postInput,)
  }
);}




export const getCreatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<PostInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<PostInput>}, TContext> => {

const mutationKey = ['createPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPost>>, {data: BodyType<PostInput>}> = (props) => {
          const {data} = props ?? {};

          return  createPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createPost>>>
    export type CreatePostMutationBody = BodyType<PostInput>
    export type CreatePostMutationError = ErrorType<unknown>

    export const useCreatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPost>>, TError,{data: BodyType<PostInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPost>>,
        TError,
        {data: BodyType<PostInput>},
        TContext
      > => {
      return useMutation(getCreatePostMutationOptions(options));
    }

export const getGetPopularPostsUrl = (params?: GetPopularPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/posts/popular?${stringifiedParams}` : `/api/posts/popular`
}

/**
 * @summary Hot posts across all boards
 */
export const getPopularPosts = async (params?: GetPopularPostsParams, options?: RequestInit): Promise<Post[]> => {

  return customFetch<Post[]>(getGetPopularPostsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPopularPostsQueryKey = (params?: GetPopularPostsParams,) => {
    return [
    `/api/posts/popular`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPopularPostsQueryOptions = <TData = Awaited<ReturnType<typeof getPopularPosts>>, TError = ErrorType<unknown>>(params?: GetPopularPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPopularPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPopularPostsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPopularPosts>>> = ({ signal }) => getPopularPosts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPopularPosts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPopularPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPopularPosts>>>
export type GetPopularPostsQueryError = ErrorType<unknown>


/**
 * @summary Hot posts across all boards
 */

export function useGetPopularPosts<TData = Awaited<ReturnType<typeof getPopularPosts>>, TError = ErrorType<unknown>>(
 params?: GetPopularPostsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPopularPosts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPopularPostsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetPostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

export const getPost = async (id: number, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getGetPostUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPostQueryKey = (id: number,) => {
    return [
    `/api/posts/${id}`
    ] as const;
    }


export const getGetPostQueryOptions = <TData = Awaited<ReturnType<typeof getPost>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPostQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPost>>> = ({ signal }) => getPost(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPostQueryResult = NonNullable<Awaited<ReturnType<typeof getPost>>>
export type GetPostQueryError = ErrorType<unknown>



export function useGetPost<TData = Awaited<ReturnType<typeof getPost>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPost>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPostQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdatePostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

export const updatePost = async (id: number,
    postUpdate: PostUpdate, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getUpdatePostUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postUpdate,)
  }
);}




export const getUpdatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{id: number;data: BodyType<PostUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{id: number;data: BodyType<PostUpdate>}, TContext> => {

const mutationKey = ['updatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePost>>, {id: number;data: BodyType<PostUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePost(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePost>>>
    export type UpdatePostMutationBody = BodyType<PostUpdate>
    export type UpdatePostMutationError = ErrorType<unknown>

    export const useUpdatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePost>>, TError,{id: number;data: BodyType<PostUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updatePost>>,
        TError,
        {id: number;data: BodyType<PostUpdate>},
        TContext
      > => {
      return useMutation(getUpdatePostMutationOptions(options));
    }

export const getDeletePostUrl = (id: number,) => {




  return `/api/posts/${id}`
}

export const deletePost = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeletePostUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeletePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext> => {

const mutationKey = ['deletePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePost>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deletePost(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePost>>>

    export type DeletePostMutationError = ErrorType<unknown>

    export const useDeletePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePost>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePost>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeletePostMutationOptions(options));
    }

export const getVotePostUrl = (id: number,) => {




  return `/api/posts/${id}/vote`
}

export const votePost = async (id: number,
    voteInput: VoteInput, options?: RequestInit): Promise<Post> => {

  return customFetch<Post>(getVotePostUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voteInput,)
  }
);}




export const getVotePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof votePost>>, TError,{id: number;data: BodyType<VoteInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof votePost>>, TError,{id: number;data: BodyType<VoteInput>}, TContext> => {

const mutationKey = ['votePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof votePost>>, {id: number;data: BodyType<VoteInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  votePost(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VotePostMutationResult = NonNullable<Awaited<ReturnType<typeof votePost>>>
    export type VotePostMutationBody = BodyType<VoteInput>
    export type VotePostMutationError = ErrorType<unknown>

    export const useVotePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof votePost>>, TError,{id: number;data: BodyType<VoteInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof votePost>>,
        TError,
        {id: number;data: BodyType<VoteInput>},
        TContext
      > => {
      return useMutation(getVotePostMutationOptions(options));
    }

export const getListCommentsUrl = (postId: number,) => {




  return `/api/posts/${postId}/comments`
}

export const listComments = async (postId: number, options?: RequestInit): Promise<Comment[]> => {

  return customFetch<Comment[]>(getListCommentsUrl(postId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCommentsQueryKey = (postId: number,) => {
    return [
    `/api/posts/${postId}/comments`
    ] as const;
    }


export const getListCommentsQueryOptions = <TData = Awaited<ReturnType<typeof listComments>>, TError = ErrorType<unknown>>(postId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCommentsQueryKey(postId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listComments>>> = ({ signal }) => listComments(postId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(postId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof listComments>>>
export type ListCommentsQueryError = ErrorType<unknown>



export function useListComments<TData = Awaited<ReturnType<typeof listComments>>, TError = ErrorType<unknown>>(
 postId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listComments>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCommentsQueryOptions(postId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateCommentUrl = (postId: number,) => {




  return `/api/posts/${postId}/comments`
}

export const createComment = async (postId: number,
    commentInput: CommentInput, options?: RequestInit): Promise<Comment> => {

  return customFetch<Comment>(getCreateCommentUrl(postId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      commentInput,)
  }
);}




export const getCreateCommentMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{postId: number;data: BodyType<CommentInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{postId: number;data: BodyType<CommentInput>}, TContext> => {

const mutationKey = ['createComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createComment>>, {postId: number;data: BodyType<CommentInput>}> = (props) => {
          const {postId,data} = props ?? {};

          return  createComment(postId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof createComment>>>
    export type CreateCommentMutationBody = BodyType<CommentInput>
    export type CreateCommentMutationError = ErrorType<unknown>

    export const useCreateComment = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createComment>>, TError,{postId: number;data: BodyType<CommentInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createComment>>,
        TError,
        {postId: number;data: BodyType<CommentInput>},
        TContext
      > => {
      return useMutation(getCreateCommentMutationOptions(options));
    }

export const getDeleteCommentUrl = (id: number,) => {




  return `/api/comments/${id}`
}

export const deleteComment = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteCommentUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCommentMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteComment>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteComment(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCommentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteComment>>>

    export type DeleteCommentMutationError = ErrorType<unknown>

    export const useDeleteComment = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteComment>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteComment>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteCommentMutationOptions(options));
    }

export const getListPredictionsUrl = (params?: ListPredictionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/predictions?${stringifiedParams}` : `/api/predictions`
}

export const listPredictions = async (params?: ListPredictionsParams, options?: RequestInit): Promise<Prediction[]> => {

  return customFetch<Prediction[]>(getListPredictionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPredictionsQueryKey = (params?: ListPredictionsParams,) => {
    return [
    `/api/predictions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof listPredictions>>, TError = ErrorType<unknown>>(params?: ListPredictionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPredictions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPredictionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPredictions>>> = ({ signal }) => listPredictions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPredictions>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof listPredictions>>>
export type ListPredictionsQueryError = ErrorType<unknown>



export function useListPredictions<TData = Awaited<ReturnType<typeof listPredictions>>, TError = ErrorType<unknown>>(
 params?: ListPredictionsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPredictions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPredictionsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreatePredictionUrl = () => {




  return `/api/predictions`
}

export const createPrediction = async (predictionInput: PredictionInput, options?: RequestInit): Promise<Prediction> => {

  return customFetch<Prediction>(getCreatePredictionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      predictionInput,)
  }
);}




export const getCreatePredictionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrediction>>, TError,{data: BodyType<PredictionInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPrediction>>, TError,{data: BodyType<PredictionInput>}, TContext> => {

const mutationKey = ['createPrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPrediction>>, {data: BodyType<PredictionInput>}> = (props) => {
          const {data} = props ?? {};

          return  createPrediction(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof createPrediction>>>
    export type CreatePredictionMutationBody = BodyType<PredictionInput>
    export type CreatePredictionMutationError = ErrorType<unknown>

    export const useCreatePrediction = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrediction>>, TError,{data: BodyType<PredictionInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPrediction>>,
        TError,
        {data: BodyType<PredictionInput>},
        TContext
      > => {
      return useMutation(getCreatePredictionMutationOptions(options));
    }

export const getGetPredictionLeaderboardUrl = (params?: GetPredictionLeaderboardParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/predictions/leaderboard?${stringifiedParams}` : `/api/predictions/leaderboard`
}

/**
 * @summary Top predictors ranked by accuracy and points
 */
export const getPredictionLeaderboard = async (params?: GetPredictionLeaderboardParams, options?: RequestInit): Promise<LeaderboardEntry[]> => {

  return customFetch<LeaderboardEntry[]>(getGetPredictionLeaderboardUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPredictionLeaderboardQueryKey = (params?: GetPredictionLeaderboardParams,) => {
    return [
    `/api/predictions/leaderboard`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPredictionLeaderboardQueryOptions = <TData = Awaited<ReturnType<typeof getPredictionLeaderboard>>, TError = ErrorType<unknown>>(params?: GetPredictionLeaderboardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPredictionLeaderboard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPredictionLeaderboardQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPredictionLeaderboard>>> = ({ signal }) => getPredictionLeaderboard(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPredictionLeaderboard>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPredictionLeaderboardQueryResult = NonNullable<Awaited<ReturnType<typeof getPredictionLeaderboard>>>
export type GetPredictionLeaderboardQueryError = ErrorType<unknown>


/**
 * @summary Top predictors ranked by accuracy and points
 */

export function useGetPredictionLeaderboard<TData = Awaited<ReturnType<typeof getPredictionLeaderboard>>, TError = ErrorType<unknown>>(
 params?: GetPredictionLeaderboardParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPredictionLeaderboard>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPredictionLeaderboardQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMeUrl = () => {




  return `/api/users/me`
}

/**
 * @summary Get current user profile
 */
export const getMe = async ( options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/users/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<unknown>


/**
 * @summary Get current user profile
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateMeUrl = () => {




  return `/api/users/me`
}

export const updateMe = async (userUpdate: UserUpdate, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userUpdate,)
  }
);}




export const getUpdateMeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext> => {

const mutationKey = ['updateMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMe>>, {data: BodyType<UserUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateMe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
    export type UpdateMeMutationBody = BodyType<UserUpdate>
    export type UpdateMeMutationError = ErrorType<unknown>

    export const useUpdateMe = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateMe>>,
        TError,
        {data: BodyType<UserUpdate>},
        TContext
      > => {
      return useMutation(getUpdateMeMutationOptions(options));
    }

export const getGetMyCardsUrl = () => {




  return `/api/users/me/cards`
}

/**
 * @summary Get player cards owned by current user
 */
export const getMyCards = async ( options?: RequestInit): Promise<PlayerCard[]> => {

  return customFetch<PlayerCard[]>(getGetMyCardsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMyCardsQueryKey = () => {
    return [
    `/api/users/me/cards`
    ] as const;
    }


export const getGetMyCardsQueryOptions = <TData = Awaited<ReturnType<typeof getMyCards>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyCards>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyCardsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyCards>>> = ({ signal }) => getMyCards({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyCards>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMyCardsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyCards>>>
export type GetMyCardsQueryError = ErrorType<unknown>


/**
 * @summary Get player cards owned by current user
 */

export function useGetMyCards<TData = Awaited<ReturnType<typeof getMyCards>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyCards>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMyCardsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMyAchievementsUrl = () => {




  return `/api/users/me/achievements`
}

export const getMyAchievements = async ( options?: RequestInit): Promise<Achievement[]> => {

  return customFetch<Achievement[]>(getGetMyAchievementsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMyAchievementsQueryKey = () => {
    return [
    `/api/users/me/achievements`
    ] as const;
    }


export const getGetMyAchievementsQueryOptions = <TData = Awaited<ReturnType<typeof getMyAchievements>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyAchievements>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyAchievementsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyAchievements>>> = ({ signal }) => getMyAchievements({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyAchievements>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMyAchievementsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyAchievements>>>
export type GetMyAchievementsQueryError = ErrorType<unknown>



export function useGetMyAchievements<TData = Awaited<ReturnType<typeof getMyAchievements>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyAchievements>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMyAchievementsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getDailyCheckinUrl = () => {




  return `/api/users/checkin`
}

/**
 * @summary Daily check-in to earn points
 */
export const dailyCheckin = async ( options?: RequestInit): Promise<CheckinResult> => {

  return customFetch<CheckinResult>(getDailyCheckinUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getDailyCheckinMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dailyCheckin>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof dailyCheckin>>, TError,void, TContext> => {

const mutationKey = ['dailyCheckin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dailyCheckin>>, void> = () => {


          return  dailyCheckin(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DailyCheckinMutationResult = NonNullable<Awaited<ReturnType<typeof dailyCheckin>>>

    export type DailyCheckinMutationError = ErrorType<unknown>

    /**
 * @summary Daily check-in to earn points
 */
export const useDailyCheckin = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dailyCheckin>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof dailyCheckin>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDailyCheckinMutationOptions(options));
    }

export const getRegisterUserUrl = () => {




  return `/api/users/register`
}

export const registerUser = async (registerInput: RegisterInput, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getRegisterUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerInput,)
  }
);}




export const getRegisterUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: BodyType<RegisterInput>}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: BodyType<RegisterInput>}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = BodyType<RegisterInput>
    export type RegisterUserMutationError = ErrorType<unknown>

    export const useRegisterUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: BodyType<RegisterInput>},
        TContext
      > => {
      return useMutation(getRegisterUserMutationOptions(options));
    }

export const getLoginUserUrl = () => {




  return `/api/users/login`
}

export const loginUser = async (loginInput: LoginInput, options?: RequestInit): Promise<AuthResult> => {

  return customFetch<AuthResult>(getLoginUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginInput,)
  }
);}




export const getLoginUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: BodyType<LoginInput>}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: BodyType<LoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = BodyType<LoginInput>
    export type LoginUserMutationError = ErrorType<unknown>

    export const useLoginUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: BodyType<LoginInput>},
        TContext
      > => {
      return useMutation(getLoginUserMutationOptions(options));
    }

export const getLogoutUserUrl = () => {




  return `/api/users/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getLogoutUserUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLogoutUserMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, void> = () => {


          return  logoutUser(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>

    export type LogoutUserMutationError = ErrorType<unknown>

    export const useLogoutUser = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutUserMutationOptions(options));
    }

export const getGetUserUrl = (id: number,) => {




  return `/api/users/${id}`
}

export const getUser = async (id: number, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetUserUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserQueryKey = (id: number,) => {
    return [
    `/api/users/${id}`
    ] as const;
    }


export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = ErrorType<unknown>



export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListHighlightsUrl = (params?: ListHighlightsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/highlights?${stringifiedParams}` : `/api/highlights`
}

export const listHighlights = async (params?: ListHighlightsParams, options?: RequestInit): Promise<Highlight[]> => {

  return customFetch<Highlight[]>(getListHighlightsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListHighlightsQueryKey = (params?: ListHighlightsParams,) => {
    return [
    `/api/highlights`, ...(params ? [params] : [])
    ] as const;
    }


export const getListHighlightsQueryOptions = <TData = Awaited<ReturnType<typeof listHighlights>>, TError = ErrorType<unknown>>(params?: ListHighlightsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listHighlights>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListHighlightsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listHighlights>>> = ({ signal }) => listHighlights(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listHighlights>>, TError, TData> & { queryKey: QueryKey }
}

export type ListHighlightsQueryResult = NonNullable<Awaited<ReturnType<typeof listHighlights>>>
export type ListHighlightsQueryError = ErrorType<unknown>



export function useListHighlights<TData = Awaited<ReturnType<typeof listHighlights>>, TError = ErrorType<unknown>>(
 params?: ListHighlightsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listHighlights>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListHighlightsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateHighlightUrl = () => {




  return `/api/highlights`
}

export const createHighlight = async (highlightInput: HighlightInput, options?: RequestInit): Promise<Highlight> => {

  return customFetch<Highlight>(getCreateHighlightUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      highlightInput,)
  }
);}




export const getCreateHighlightMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createHighlight>>, TError,{data: BodyType<HighlightInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createHighlight>>, TError,{data: BodyType<HighlightInput>}, TContext> => {

const mutationKey = ['createHighlight'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createHighlight>>, {data: BodyType<HighlightInput>}> = (props) => {
          const {data} = props ?? {};

          return  createHighlight(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateHighlightMutationResult = NonNullable<Awaited<ReturnType<typeof createHighlight>>>
    export type CreateHighlightMutationBody = BodyType<HighlightInput>
    export type CreateHighlightMutationError = ErrorType<unknown>

    export const useCreateHighlight = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createHighlight>>, TError,{data: BodyType<HighlightInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createHighlight>>,
        TError,
        {data: BodyType<HighlightInput>},
        TContext
      > => {
      return useMutation(getCreateHighlightMutationOptions(options));
    }

export const getGetHighlightUrl = (id: number,) => {




  return `/api/highlights/${id}`
}

export const getHighlight = async (id: number, options?: RequestInit): Promise<Highlight> => {

  return customFetch<Highlight>(getGetHighlightUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHighlightQueryKey = (id: number,) => {
    return [
    `/api/highlights/${id}`
    ] as const;
    }


export const getGetHighlightQueryOptions = <TData = Awaited<ReturnType<typeof getHighlight>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHighlight>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHighlightQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHighlight>>> = ({ signal }) => getHighlight(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHighlight>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHighlightQueryResult = NonNullable<Awaited<ReturnType<typeof getHighlight>>>
export type GetHighlightQueryError = ErrorType<unknown>



export function useGetHighlight<TData = Awaited<ReturnType<typeof getHighlight>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHighlight>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHighlightQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getLikeHighlightUrl = (id: number,) => {




  return `/api/highlights/${id}/like`
}

export const likeHighlight = async (id: number, options?: RequestInit): Promise<Highlight> => {

  return customFetch<Highlight>(getLikeHighlightUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLikeHighlightMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof likeHighlight>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof likeHighlight>>, TError,{id: number}, TContext> => {

const mutationKey = ['likeHighlight'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof likeHighlight>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  likeHighlight(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LikeHighlightMutationResult = NonNullable<Awaited<ReturnType<typeof likeHighlight>>>

    export type LikeHighlightMutationError = ErrorType<unknown>

    export const useLikeHighlight = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof likeHighlight>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof likeHighlight>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getLikeHighlightMutationOptions(options));
    }

export const getGetHomeSummaryUrl = () => {




  return `/api/stats/home-summary`
}

/**
 * @summary Homepage dashboard summary
 */
export const getHomeSummary = async ( options?: RequestInit): Promise<HomeSummary> => {

  return customFetch<HomeSummary>(getGetHomeSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHomeSummaryQueryKey = () => {
    return [
    `/api/stats/home-summary`
    ] as const;
    }


export const getGetHomeSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getHomeSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHomeSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHomeSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHomeSummary>>> = ({ signal }) => getHomeSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHomeSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHomeSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getHomeSummary>>>
export type GetHomeSummaryQueryError = ErrorType<unknown>


/**
 * @summary Homepage dashboard summary
 */

export function useGetHomeSummary<TData = Awaited<ReturnType<typeof getHomeSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHomeSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHomeSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAiMatchPredictionsUrl = () => {




  return `/api/stats/ai-prediction`
}

/**
 * @summary AI match predictions for today
 */
export const getAiMatchPredictions = async ( options?: RequestInit): Promise<AiMatchPrediction[]> => {

  return customFetch<AiMatchPrediction[]>(getGetAiMatchPredictionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAiMatchPredictionsQueryKey = () => {
    return [
    `/api/stats/ai-prediction`
    ] as const;
    }


export const getGetAiMatchPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof getAiMatchPredictions>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAiMatchPredictions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAiMatchPredictionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAiMatchPredictions>>> = ({ signal }) => getAiMatchPredictions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAiMatchPredictions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAiMatchPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAiMatchPredictions>>>
export type GetAiMatchPredictionsQueryError = ErrorType<unknown>


/**
 * @summary AI match predictions for today
 */

export function useGetAiMatchPredictions<TData = Awaited<ReturnType<typeof getAiMatchPredictions>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAiMatchPredictions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAiMatchPredictionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetHomerunPredictionsUrl = () => {




  return `/api/stats/homerun-prediction`
}

/**
 * @summary Today's homerun candidates
 */
export const getHomerunPredictions = async ( options?: RequestInit): Promise<HomerunCandidate[]> => {

  return customFetch<HomerunCandidate[]>(getGetHomerunPredictionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHomerunPredictionsQueryKey = () => {
    return [
    `/api/stats/homerun-prediction`
    ] as const;
    }


export const getGetHomerunPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof getHomerunPredictions>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHomerunPredictions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHomerunPredictionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHomerunPredictions>>> = ({ signal }) => getHomerunPredictions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHomerunPredictions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetHomerunPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof getHomerunPredictions>>>
export type GetHomerunPredictionsQueryError = ErrorType<unknown>


/**
 * @summary Today's homerun candidates
 */

export function useGetHomerunPredictions<TData = Awaited<ReturnType<typeof getHomerunPredictions>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getHomerunPredictions>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetHomerunPredictionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListNotificationsUrl = () => {




  return `/api/notifications`
}

export const listNotifications = async ( options?: RequestInit): Promise<Notification[]> => {

  return customFetch<Notification[]>(getListNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListNotificationsQueryKey = () => {
    return [
    `/api/notifications`
    ] as const;
    }


export const getListNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotifications>>> = ({ signal }) => listNotifications({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData> & { queryKey: QueryKey }
}

export type ListNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof listNotifications>>>
export type ListNotificationsQueryError = ErrorType<unknown>



export function useListNotifications<TData = Awaited<ReturnType<typeof listNotifications>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listNotifications>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListNotificationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getMarkNotificationReadUrl = (id: number,) => {




  return `/api/notifications/${id}/read`
}

export const markNotificationRead = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getMarkNotificationReadUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getMarkNotificationReadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError,{id: number}, TContext> => {

const mutationKey = ['markNotificationRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markNotificationRead>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  markNotificationRead(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkNotificationReadMutationResult = NonNullable<Awaited<ReturnType<typeof markNotificationRead>>>

    export type MarkNotificationReadMutationError = ErrorType<unknown>

    export const useMarkNotificationRead = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationRead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof markNotificationRead>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getMarkNotificationReadMutationOptions(options));
    }

